task: nerf
gpus: [1] # set gpu device number
exp_name: "nerf"
scene: "colmap"

train_dataset_module: 'lib.datasets.nerf.colmap'
train_dataset_path: 'lib/datasets/nerf/comlap.py'

test_dataset_module: 'lib.datasets.nerf.colmap'
test_dataset_path: 'lib/datasets/nerf/colmap.py'

network_module: 'lib.networks.nerf.network'
network_path: 'lib/networks/nerf/network.py'

renderer_module: 'lib.networks.nerf.renderer.volume_renderer'
renderer_path: 'lib/networks/nerf/renderer/volume_renderer.py'

loss_module: 'lib.train.trainers.nerf'
loss_path: 'lib/train/trainers/nerf.py'

evaluator_module: 'lib.evaluators.nerf'
evaluator_path: 'lib/evaluators/nerf.py'

visualizer_module: 'lib.visualizers.nerf'
visualizer_path: 'lib/visualizers/nerf.py'

task_arg:
  N_rays: 1024 # number of rays in each batch
  chunk_size: 4096 # number of rays processed in parallel
  white_bkgd: 1 # use white background
  N_samples: 64 # number of samples per ray in coarse network
  N_importance: 128 # number of samples per ray in fine network
  no_batching: True # True for synthetic datasets
  use_viewdirs: True # whether use full 5D input instead of 3D
  lindisp: False
  perturb: 1
  raw_noise_std: 0
  use_pe: True # whether use positional encoding
  test_skip: 1 # will load 1/N images from test/val sets, useful for large datasets
  precrop_iters: 500
  precrop_frac: 0.5

network:
  nerf:
    W: 256 # width of network
    D: 8 # depth of network
    V_D: 1 # appearance depth
    skips: [4]
  xyz_encoder: # encoder for location
    type: "frequency"
    input_dim: 3 # dimensions of input data
    freq: 10 # dimensions of encoding location
  dir_encoder: # encoder for direction
    type: "frequency"
    input_dim: 3 # dimensions of input data
    freq: 4 # dimensions of encoding direction

train_dataset:
  data_root: "data/nerf_synthetic"
  split: "train"
  input_ratio: 1. # whether to downsampling the image, you can set it to 0.5 to acclerate training
  cams: [0, -1, 1] # input cameras, you can use this variable to select training images
  H: 800
  W: 800

test_dataset:
  data_root: "data/nerf_synthetic"
  split: "test"
  input_ratio: 0.5
  cams: [0, -1, 100]
  H: 800
  W: 800

train:
  single_view: False
  batch_size: 1
  lr: 5e-4 # learning rate
  weight_decay: 0.
  epoch: 400
  optim: 'adam'
  scheduler:
    type: "exponential"
    gamma: 0.1
    decay_epochs: 500 # original 1000
  num_workers: 4

test:
  batch_size: 1

eval:
  whole_img: True

ep_iter: 500 # number of iterations in each epoch
save_ep: 20
eval_ep: 20 # 20000 iterations
save_latest_ep: 10 # 5000 iterations
log_interval: 10
